### ISSUE TITLE
Check if draggableContainer or draggableView is null

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/drag-to-close#16]
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: PID: 24380
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationOnScreen(int[])' on a null object reference
                      at com.davidmiguel.dragtoclose.DragToClose.isViewTouched(DragToClose.java:328)
                      at com.davidmiguel.dragtoclose.DragToClose.onTouchEvent(DragToClose.java:121)
                      at android.view.View.dispatchTouchEvent(View.java:10779)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2859)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2535)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:582)
                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1885)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:3240)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:544)
                      at android.view.View.dispatchPointerEvent(View.java:11008)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5162)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5014)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4691)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4748)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7099)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7031)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6992)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7209)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java:323)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:6776)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by davidmigloz** [comment]
Now it triggers a `IllegalArgumentException` with a descriptive message instead of `NullPointerException`.
